INSERT INTO FOOD(name,price) VALUES ('BIRIYANI',250.00);
INSERT INTO FOOD(name,price) VALUES ('BURGER',200.00);
INSERT INTO FOOD(name,price) VALUES ('PIZZA',500.00);
INSERT INTO FOOD(name,price) VALUES ('FRIEDRICE',100.00);
INSERT INTO FOOD(name,price) VALUES ('SWEET',100.00);
INSERT INTO FOOD(name,price) VALUES ('CHOLEBHATURE',60.00);
INSERT INTO FOOD(name,price) VALUES ('ICE CREAM',150.00);